apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-frontend-deployment
spec:
  replicas: 1 # Adjust as needed
  selector:
    matchLabels:
      app: node-frontend
  template:
    metadata:
      labels:
        app: node-frontend
    spec:
      containers:
        - name: node-frontend
          image: roshinmsk/node_frontend:0.0.1
          ports:
            - containerPort: 3000
